/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author ranul
 */
public class Access extends javax.swing.JFrame {

    /**
     * Creates new form Access
     */
    public Access() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AccessPanel = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        qService_pnl = new javax.swing.JPanel();
        UName_Lbl = new javax.swing.JLabel();
        Password_Lbl = new javax.swing.JLabel();
        password_Txt = new javax.swing.JPasswordField();
        username_Txt = new javax.swing.JTextField();
        SelectionLbl = new javax.swing.JLabel();
        Services_Lbl = new javax.swing.JLabel();
        role_DD = new javax.swing.JComboBox<>();
        bankName_Lbl = new javax.swing.JLabel();
        Slogan_Lbl = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Trademark = new javax.swing.JLabel();
        login_Btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusTraversalPolicyProvider(true);
        setLocationByPlatform(true);
        setResizable(false);
        setSize(new java.awt.Dimension(923, 596));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });

        AccessPanel.setBackground(new java.awt.Color(0, 123, 146));
        AccessPanel.setMaximumSize(new java.awt.Dimension(1200, 800));
        AccessPanel.setMinimumSize(new java.awt.Dimension(1200, 800));
        AccessPanel.setPreferredSize(new java.awt.Dimension(1200, 800));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/QUINN_LOGO.gif"))); // NOI18N
        logo.setText("jLabel2");

        qService_pnl.setBackground(new java.awt.Color(18, 63, 72));

        UName_Lbl.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        UName_Lbl.setForeground(new java.awt.Color(255, 255, 255));
        UName_Lbl.setText("Username");

        Password_Lbl.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        Password_Lbl.setForeground(new java.awt.Color(255, 255, 255));
        Password_Lbl.setText("Password");

        password_Txt.setBackground(new java.awt.Color(254, 252, 217));
        password_Txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        password_Txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password_TxtActionPerformed(evt);
            }
        });

        username_Txt.setBackground(new java.awt.Color(254, 252, 217));
        username_Txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        username_Txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                username_TxtKeyPressed(evt);
            }
        });

        SelectionLbl.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        SelectionLbl.setForeground(new java.awt.Color(255, 255, 255));
        SelectionLbl.setText("Select:");

        Services_Lbl.setBackground(new java.awt.Color(18, 63, 150));
        Services_Lbl.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        Services_Lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Services_Lbl.setText("QUINN BANKING SERVICES");

        role_DD.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        role_DD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--SELECT ROLE--", "Bank Teller", "Bank Manager", "Bank Data Administrator", " " }));

        javax.swing.GroupLayout qService_pnlLayout = new javax.swing.GroupLayout(qService_pnl);
        qService_pnl.setLayout(qService_pnlLayout);
        qService_pnlLayout.setHorizontalGroup(
            qService_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Services_Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(qService_pnlLayout.createSequentialGroup()
                .addGap(362, 362, 362)
                .addGroup(qService_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(UName_Lbl)
                    .addComponent(Password_Lbl)
                    .addComponent(SelectionLbl))
                .addGap(44, 44, 44)
                .addGroup(qService_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(username_Txt)
                    .addComponent(role_DD, 0, 235, Short.MAX_VALUE)
                    .addComponent(password_Txt))
                .addContainerGap(363, Short.MAX_VALUE))
        );
        qService_pnlLayout.setVerticalGroup(
            qService_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, qService_pnlLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Services_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(qService_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UName_Lbl)
                    .addComponent(username_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(qService_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Password_Lbl))
                .addGap(18, 18, 18)
                .addGroup(qService_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SelectionLbl)
                    .addComponent(role_DD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(129, 129, 129))
        );

        bankName_Lbl.setFont(new java.awt.Font("Bodoni MT", 0, 36)); // NOI18N
        bankName_Lbl.setForeground(new java.awt.Color(255, 255, 255));
        bankName_Lbl.setText("QUINN BANK");

        Slogan_Lbl.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        Slogan_Lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Slogan_Lbl.setText("Guarding Day & Night");

        jPanel2.setBackground(new java.awt.Color(10, 10, 18));

        Trademark.setBackground(new java.awt.Color(0, 0, 51));
        Trademark.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Trademark.setForeground(new java.awt.Color(255, 255, 255));
        Trademark.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Trademark.setText("PROPERTY OF QUINN INCORPORATION");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Trademark, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Trademark, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        login_Btn.setBackground(new java.awt.Color(41, 169, 25));
        login_Btn.setFont(new java.awt.Font("Constantia", 1, 24)); // NOI18N
        login_Btn.setForeground(new java.awt.Color(255, 255, 255));
        login_Btn.setText("LOGIN");
        login_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_BtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AccessPanelLayout = new javax.swing.GroupLayout(AccessPanel);
        AccessPanel.setLayout(AccessPanelLayout);
        AccessPanelLayout.setHorizontalGroup(
            AccessPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AccessPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(login_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(460, 460, 460))
            .addGroup(AccessPanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(AccessPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AccessPanelLayout.createSequentialGroup()
                        .addComponent(qService_pnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 43, Short.MAX_VALUE))
                    .addGroup(AccessPanelLayout.createSequentialGroup()
                        .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(AccessPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bankName_Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Slogan_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59))))
        );
        AccessPanelLayout.setVerticalGroup(
            AccessPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AccessPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(AccessPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AccessPanelLayout.createSequentialGroup()
                        .addComponent(bankName_Lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Slogan_Lbl))
                    .addComponent(logo))
                .addGap(48, 48, 48)
                .addComponent(qService_pnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(login_Btn)
                .addGap(38, 38, 38)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(AccessPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AccessPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 714, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void password_TxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password_TxtActionPerformed

    }//GEN-LAST:event_password_TxtActionPerformed

    private void login_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_BtnActionPerformed
        //Opens the Relevant Frame for Authorised User

//      MORE AUTHETICATION FUNCTIONS WILL BE ADDED WITH DB IMPLEMENTATION 27/10/2019
        JComboBox cmb = (role_DD);
        Object selected = cmb.getSelectedItem();

        if (cmb.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null,
                    "Please Select your role position to continue.",
                    "WARNING !",
                    JOptionPane.WARNING_MESSAGE);
        }
        if (username_Txt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null,
                    "Please Enter Your Credentials.",
                    "ERROR !",
                    JOptionPane.ERROR_MESSAGE);
        } else if (selected.toString().equals("Bank Teller")) {
            Teller t1 = new Teller();
            t1.setVisible(true);
            //closes the login form prevent unnecessary tab creation
            this.setVisible(false);
        } else if (selected.toString().equals("Bank Manager")) {
            Manager m1 = new Manager();
            m1.setVisible(true);
            //closes the login form prevent unnecessary tab creation
            this.setVisible(false);
        } else if (selected.toString().equals("Bank Data Administrator")) {
            AdminPanel a1 = new AdminPanel();
            a1.setVisible(true);
            //closes the login form prevent unnecessary tab creation
            this.setVisible(false);
        }

    }//GEN-LAST:event_login_BtnActionPerformed

    private void username_TxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_username_TxtKeyPressed

    }//GEN-LAST:event_username_TxtKeyPressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged

    }//GEN-LAST:event_formMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Access.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Access.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Access.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Access.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Access().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AccessPanel;
    private javax.swing.JLabel Password_Lbl;
    private javax.swing.JLabel SelectionLbl;
    private javax.swing.JLabel Services_Lbl;
    private javax.swing.JLabel Slogan_Lbl;
    private javax.swing.JLabel Trademark;
    private javax.swing.JLabel UName_Lbl;
    private javax.swing.JLabel bankName_Lbl;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton login_Btn;
    private javax.swing.JLabel logo;
    private javax.swing.JPasswordField password_Txt;
    private javax.swing.JPanel qService_pnl;
    private javax.swing.JComboBox<String> role_DD;
    private javax.swing.JTextField username_Txt;
    // End of variables declaration//GEN-END:variables
}
