
import java.awt.Color;
import java.text.SimpleDateFormat;  
import java.util.Date; 
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ranul
 */
public class Teller extends javax.swing.JFrame{
    static int basic = 250000000;
    static int bonus = 450000000;
    static int premier = 750000000;
    /**
     * Creates new form Teller
     */
    public Teller() {
        initComponents(); 
        date.setText(java.time.LocalDate.now().toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        logout = new javax.swing.JMenuItem();
        jDialog1 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        NewUser = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel4 = new javax.swing.JPanel();
        ClearSA = new javax.swing.JButton();
        CheckSA = new javax.swing.JButton();
        SubmitSA = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        dAccount = new javax.swing.JLabel();
        DAccno = new javax.swing.JTextField();
        holderName = new javax.swing.JTextField();
        dName = new javax.swing.JLabel();
        dBalance = new javax.swing.JLabel();
        currentBalance = new javax.swing.JTextField();
        DEPAmount = new javax.swing.JTextField();
        dAmmount = new javax.swing.JLabel();
        dType = new javax.swing.JLabel();
        ACCType = new javax.swing.JTextField();
        DepositBonus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        bonusINFO = new javax.swing.JTextArea();
        jLabel21 = new javax.swing.JLabel();
        FinalDeposit = new javax.swing.JTextField();
        jSplitPane5 = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        ClearSA1 = new javax.swing.JButton();
        CheckSA1 = new javax.swing.JButton();
        SubmitSA1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        wACCT = new javax.swing.JLabel();
        wName = new javax.swing.JLabel();
        wBalance = new javax.swing.JLabel();
        WHolder = new javax.swing.JTextField();
        DCurrentBalance = new javax.swing.JTextField();
        WAccno = new javax.swing.JTextField();
        WDRL = new javax.swing.JLabel();
        Dwithdraw = new javax.swing.JTextField();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        interestINFO = new javax.swing.JTextArea();
        CheckSA3 = new javax.swing.JButton();
        processInterest = new javax.swing.JButton();
        day = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jSplitPane4 = new javax.swing.JSplitPane();
        jPanel8 = new javax.swing.JPanel();
        Generate = new javax.swing.JButton();
        RSubmit = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        ACCTType = new javax.swing.JLabel();
        FName = new javax.swing.JLabel();
        ACCTNumber = new javax.swing.JLabel();
        PhoneNum = new javax.swing.JLabel();
        IDeposit = new javax.swing.JLabel();
        Mail = new javax.swing.JLabel();
        NewFName = new javax.swing.JTextField();
        LName = new javax.swing.JLabel();
        NewLName = new javax.swing.JTextField();
        listOfAccountTypes = new javax.swing.JComboBox<>();
        NewMail = new javax.swing.JTextField();
        IDepositAMT = new javax.swing.JTextField();
        txtGeneratedAccountNo = new javax.swing.JTextField();
        NewPhoneNum = new javax.swing.JTextField();
        accNoGen = new javax.swing.JButton();
        accNoGen1 = new javax.swing.JButton();
        PNumber = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        jMenu1.setText("Menu");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jMenu1.add(logout);

        jMenuBar1.add(jMenu1);

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(997, 598));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        NewUser.setBackground(new java.awt.Color(255, 204, 255));

        jTabbedPane2.setBackground(new java.awt.Color(255, 255, 204));

        ClearSA.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ClearSA.setText("Clear");

        CheckSA.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CheckSA.setText("Check");

        SubmitSA.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SubmitSA.setText("Submit");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ClearSA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(CheckSA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(SubmitSA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(ClearSA, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(CheckSA, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 319, Short.MAX_VALUE)
                .addComponent(SubmitSA, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jSplitPane1.setLeftComponent(jPanel4);

        dAccount.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        dAccount.setText("Account No:");

        DAccno.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        DAccno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DAccnoActionPerformed(evt);
            }
        });

        holderName.setEditable(false);
        holderName.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        holderName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                holderNameActionPerformed(evt);
            }
        });

        dName.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        dName.setText("Holder Name:");

        dBalance.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        dBalance.setText("Current Balance: ");

        currentBalance.setEditable(false);
        currentBalance.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        currentBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentBalanceActionPerformed(evt);
            }
        });

        DEPAmount.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        DEPAmount.setText("0.00");
        DEPAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DEPAmountActionPerformed(evt);
            }
        });

        dAmmount.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        dAmmount.setText("Deposit Amount:");

        dType.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        dType.setText("Account Type");

        ACCType.setEditable(false);
        ACCType.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        ACCType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ACCTypeActionPerformed(evt);
            }
        });

        DepositBonus.setText("Bonus Calculate");
        DepositBonus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepositBonusActionPerformed(evt);
            }
        });

        bonusINFO.setEditable(false);
        bonusINFO.setColumns(20);
        bonusINFO.setRows(5);
        bonusINFO.setText("QUINN BANK DAILY DEPOSIT BONUS - DECEMBER / APRIL (SESONAL))\n\nNormal Savings : 1.25%\nBonus Savings : 3%\nPremier Savings : 7%");
        jScrollPane1.setViewportView(bonusINFO);

        jLabel21.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel21.setText("Final Total:");

        FinalDeposit.setEditable(false);
        FinalDeposit.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        FinalDeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinalDepositActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(43, 43, 43)
                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FinalDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DepositBonus))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel18Layout.createSequentialGroup()
                                .addComponent(dAccount)
                                .addGap(33, 33, 33)
                                .addComponent(DAccno, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel18Layout.createSequentialGroup()
                                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dName)
                                    .addComponent(dType)
                                    .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(dAmmount)
                                        .addComponent(dBalance)))
                                .addGap(4, 4, 4)
                                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ACCType, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                                    .addComponent(holderName, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                                    .addComponent(currentBalance, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                                    .addComponent(DEPAmount)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 657, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(242, Short.MAX_VALUE))))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dAccount)
                    .addComponent(DAccno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dName)
                    .addComponent(holderName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dBalance)
                    .addComponent(currentBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dType)
                    .addComponent(ACCType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dAmmount)
                    .addComponent(DEPAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                        .addComponent(FinalDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(DepositBonus)
                .addGap(53, 53, 53))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(jPanel5);

        jTabbedPane2.addTab("Deposits", jSplitPane1);

        ClearSA1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ClearSA1.setText("Clear");

        CheckSA1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CheckSA1.setText("Check");

        SubmitSA1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SubmitSA1.setText("Submit");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ClearSA1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(CheckSA1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(SubmitSA1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(ClearSA1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(CheckSA1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 319, Short.MAX_VALUE)
                .addComponent(SubmitSA1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jSplitPane5.setLeftComponent(jPanel2);

        wACCT.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        wACCT.setText("Account No:");

        wName.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        wName.setText("Holder Name:");

        wBalance.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        wBalance.setText("Current Balance: ");

        WHolder.setEditable(false);
        WHolder.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        WHolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WHolderActionPerformed(evt);
            }
        });

        DCurrentBalance.setEditable(false);
        DCurrentBalance.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        DCurrentBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DCurrentBalanceActionPerformed(evt);
            }
        });

        WAccno.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        WAccno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WAccnoActionPerformed(evt);
            }
        });

        WDRL.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        WDRL.setText("Withdraw Amount:");

        Dwithdraw.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        Dwithdraw.setText("0.00");
        Dwithdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DwithdrawActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(wACCT)
                                    .addComponent(wName))
                                .addGap(24, 24, 24))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(wBalance)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(WAccno, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(WHolder, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DCurrentBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(WDRL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Dwithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(637, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wACCT)
                    .addComponent(WAccno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wName)
                    .addComponent(WHolder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(wBalance)
                    .addComponent(DCurrentBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WDRL)
                    .addComponent(Dwithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(277, Short.MAX_VALUE))
        );

        jSplitPane5.setRightComponent(jPanel3);

        jTabbedPane2.addTab("Withdrawals", jSplitPane5);

        NewUser.addTab("Savings Account", jTabbedPane2);

        jTabbedPane4.setBackground(new java.awt.Color(255, 204, 255));

        interestINFO.setEditable(false);
        interestINFO.setColumns(20);
        interestINFO.setFont(new java.awt.Font("MS Gothic", 1, 18)); // NOI18N
        interestINFO.setRows(5);
        interestINFO.setText("BUILDING ECONOMY TOGETHER, EMPOWERING LIVES - QUINN BANK (MANUAL INTERST PROCESSING SYSTEM)\n\n\nDate: 22th every month (Double Interst on December Season)\n\n*Finance department verifies all interests and finals them by 28th.");
        jScrollPane2.setViewportView(interestINFO);

        CheckSA3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CheckSA3.setText("FETCH ALL ACCOUNTS");

        processInterest.setBackground(java.awt.Color.orange);
        processInterest.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        processInterest.setForeground(java.awt.Color.red);
        processInterest.setText("PROCESS INTEREST");
        processInterest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                processInterestMousePressed(evt);
            }
        });

        day.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        day.setText("Today:");

        date.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        date.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                datePropertyChange(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(day)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(processInterest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 962, Short.MAX_VALUE)
                            .addComponent(CheckSA3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(45, 45, 45))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(day)
                    .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CheckSA3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(processInterest, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(127, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("HOME", jPanel6);

        NewUser.addTab("Monthly Interests", jTabbedPane4);

        jTabbedPane5.setBackground(new java.awt.Color(204, 204, 255));

        Generate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Generate.setText("Generate");

        RSubmit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RSubmit.setText("Submit");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Generate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(RSubmit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(Generate, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 401, Short.MAX_VALUE)
                .addComponent(RSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jSplitPane4.setLeftComponent(jPanel8);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 958, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 506, Short.MAX_VALUE)
        );

        jSplitPane4.setRightComponent(jPanel9);

        jTabbedPane5.addTab("Daily Report", jSplitPane4);

        NewUser.addTab("Reports", jTabbedPane5);

        jPanel16.setBackground(new java.awt.Color(51, 51, 0));

        jPanel17.setBackground(new java.awt.Color(102, 102, 0));

        ACCTType.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        ACCTType.setText("Account Type");

        FName.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        FName.setText("First Name");

        ACCTNumber.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        ACCTNumber.setText("Account Number");

        PhoneNum.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        PhoneNum.setText("Phone                    +44");

        IDeposit.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        IDeposit.setText("Initial Deposit (£100)");

        Mail.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Mail.setText("Email");

        NewFName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        NewFName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewFNameActionPerformed(evt);
            }
        });

        LName.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        LName.setText("Last Name");

        NewLName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        listOfAccountTypes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        listOfAccountTypes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--SELECT ACCOUNT TYPE--", "NORMAL SAVINGS", "BONUS SAVINGS", "PRIMIER SAVINGS" }));

        NewMail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        IDepositAMT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        IDepositAMT.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        IDepositAMT.setText("0.00");

        txtGeneratedAccountNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtGeneratedAccountNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGeneratedAccountNoActionPerformed(evt);
            }
        });

        NewPhoneNum.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        accNoGen.setBackground(new java.awt.Color(51, 51, 51));
        accNoGen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        accNoGen.setForeground(new java.awt.Color(255, 255, 255));
        accNoGen.setText("Generate");
        accNoGen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accNoGenActionPerformed(evt);
            }
        });

        accNoGen1.setBackground(new java.awt.Color(0, 0, 153));
        accNoGen1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        accNoGen1.setForeground(new java.awt.Color(255, 255, 255));
        accNoGen1.setText("Create Account");

        PNumber.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        PNumber.setText("Passport Number / ID Number (Foreign Nationals)");

        jTextField7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel17Layout.createSequentialGroup()
                                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(ACCTType, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                                        .addComponent(Mail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(PhoneNum, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(IDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ACCTNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(listOfAccountTypes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel17Layout.createSequentialGroup()
                                        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(NewMail, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(NewPhoneNum, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(IDepositAMT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                                            .addComponent(txtGeneratedAccountNo, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(31, 31, 31)
                                        .addComponent(accNoGen))))
                            .addGroup(jPanel17Layout.createSequentialGroup()
                                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LName)
                                    .addComponent(FName))
                                .addGap(106, 106, 106)
                                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(NewLName)
                                    .addGroup(jPanel17Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(NewFName, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 215, Short.MAX_VALUE)
                        .addComponent(accNoGen1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addComponent(PNumber)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addComponent(FName)
                        .addGap(20, 20, 20)
                        .addComponent(LName))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                        .addComponent(NewFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(NewLName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ACCTType)
                    .addComponent(listOfAccountTypes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PNumber))
                .addGap(18, 18, 18)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Mail)
                    .addComponent(NewMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PhoneNum)
                    .addComponent(NewPhoneNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IDeposit)
                    .addComponent(IDepositAMT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addComponent(accNoGen1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ACCTNumber)
                            .addComponent(txtGeneratedAccountNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(accNoGen))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addContainerGap(105, Short.MAX_VALUE)
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        NewUser.addTab("NEW Customer", jPanel16);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/QUINN_LOGO.gif"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Bodoni MT", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("QUINN BANK");

        jLabel4.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Guarding Day & Night");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1)
                        .addGap(185, 185, 185)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(NewUser, javax.swing.GroupLayout.PREFERRED_SIZE, 1062, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NewUser)
                .addContainerGap())
        );

        jMenu2.setText("File");

        jMenuItem1.setText("Manager Access");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("Logout");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar2.add(jMenu2);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NewFNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewFNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewFNameActionPerformed

    private void accNoGenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accNoGenActionPerformed
        // Token Generator to Generate New Account Numbers
        String AccountType = (String) listOfAccountTypes.getSelectedItem();
         if(AccountType == "--SELECT ACCOUNT TYPE--")
        {
            JOptionPane.showMessageDialog(null, 
                              "Please An Account Type !", 
                              "Account Generation Halted!", 
                              JOptionPane.WARNING_MESSAGE);
        }
        else if(AccountType == "NORMAL SAVINGS")
        {
            int generatedAccount = basic;
            basic += 1;

            txtGeneratedAccountNo.setText(String.valueOf(generatedAccount));
        }
        else if(AccountType == "BONUS SAVINGS")
        {
            int generatedAccount = bonus;
            bonus += 1;

            txtGeneratedAccountNo.setText(String.valueOf(generatedAccount));
        }
        else if(AccountType == "PRIMIER SAVINGS")
        {
            int generatedAccount = premier;
            premier += 1;

            txtGeneratedAccountNo.setText(String.valueOf(generatedAccount));
        }
    }//GEN-LAST:event_accNoGenActionPerformed

    private void txtGeneratedAccountNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGeneratedAccountNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGeneratedAccountNoActionPerformed

    private void WHolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WHolderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WHolderActionPerformed

    private void DCurrentBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DCurrentBalanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DCurrentBalanceActionPerformed

    private void WAccnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WAccnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WAccnoActionPerformed

    private void DwithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DwithdrawActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DwithdrawActionPerformed

    private void DAccnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DAccnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DAccnoActionPerformed

    private void holderNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_holderNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_holderNameActionPerformed

    private void currentBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentBalanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_currentBalanceActionPerformed

    private void DEPAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DEPAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DEPAmountActionPerformed

    private void ACCTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ACCTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ACCTypeActionPerformed

    private void FinalDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinalDepositActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FinalDepositActionPerformed

    private void DepositBonusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepositBonusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DepositBonusActionPerformed

    private void processInterestMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_processInterestMousePressed
        // NOTIFIES AGENT ABOUT INTEREST PROCESS AND BLOCKS MULTIPLE CALCULATIONS
        // COLOUR CHANGES AND BUTTON DISABLED WHEN CLICKED
    processInterest.setBackground(Color.GREEN);
    processInterest.setForeground(Color.BLACK);
    processInterest.setEnabled(false);
    processInterest.setText("Done");
    
    }//GEN-LAST:event_processInterestMousePressed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed

    }//GEN-LAST:event_logoutActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
     
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
         //Closing Form and Reopening the Login Screeen
        Access a1 = new Access();
        a1.setVisible(true);
        //closes the login form prevent unnecessary tab creation
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void datePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_datePropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_datePropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Teller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Teller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Teller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Teller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Teller().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ACCTNumber;
    private javax.swing.JLabel ACCTType;
    private javax.swing.JTextField ACCType;
    private javax.swing.JButton CheckSA;
    private javax.swing.JButton CheckSA1;
    private javax.swing.JButton CheckSA3;
    private javax.swing.JButton ClearSA;
    private javax.swing.JButton ClearSA1;
    private javax.swing.JTextField DAccno;
    private javax.swing.JTextField DCurrentBalance;
    private javax.swing.JTextField DEPAmount;
    private javax.swing.JButton DepositBonus;
    private javax.swing.JTextField Dwithdraw;
    private javax.swing.JLabel FName;
    private javax.swing.JTextField FinalDeposit;
    private javax.swing.JButton Generate;
    private javax.swing.JLabel IDeposit;
    private javax.swing.JTextField IDepositAMT;
    private javax.swing.JLabel LName;
    private javax.swing.JLabel Mail;
    private javax.swing.JTextField NewFName;
    private javax.swing.JTextField NewLName;
    private javax.swing.JTextField NewMail;
    private javax.swing.JTextField NewPhoneNum;
    private javax.swing.JTabbedPane NewUser;
    private javax.swing.JLabel PNumber;
    private javax.swing.JLabel PhoneNum;
    private javax.swing.JButton RSubmit;
    private javax.swing.JButton SubmitSA;
    private javax.swing.JButton SubmitSA1;
    private javax.swing.JTextField WAccno;
    private javax.swing.JLabel WDRL;
    private javax.swing.JTextField WHolder;
    private javax.swing.JButton accNoGen;
    private javax.swing.JButton accNoGen1;
    private javax.swing.JTextArea bonusINFO;
    private javax.swing.JTextField currentBalance;
    private javax.swing.JLabel dAccount;
    private javax.swing.JLabel dAmmount;
    private javax.swing.JLabel dBalance;
    private javax.swing.JLabel dName;
    private javax.swing.JLabel dType;
    private javax.swing.JLabel date;
    private javax.swing.JLabel day;
    private javax.swing.JTextField holderName;
    private javax.swing.JTextArea interestINFO;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane4;
    private javax.swing.JSplitPane jSplitPane5;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JComboBox<String> listOfAccountTypes;
    private javax.swing.JMenuItem logout;
    private javax.swing.JButton processInterest;
    private javax.swing.JTextField txtGeneratedAccountNo;
    private javax.swing.JLabel wACCT;
    private javax.swing.JLabel wBalance;
    private javax.swing.JLabel wName;
    // End of variables declaration//GEN-END:variables
}
