
import java.awt.Color;
import java.text.SimpleDateFormat;  
import java.util.Date; 
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ranul
 */
public class Teller extends javax.swing.JFrame{
    static int basic = 250000000;
    static int bonus = 450000000;
    static int premier = 750000000;
    /**
     * Creates new form Teller
     */
    public Teller() {
        initComponents(); 
        date.setText(java.time.LocalDate.now().toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        logout = new javax.swing.JMenuItem();
        jDialog1 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        NewUser = new javax.swing.JTabbedPane();
        savingsAcc_pnl = new javax.swing.JTabbedPane();
        jSplitPane1 = new javax.swing.JSplitPane();
        dOption_pnl = new javax.swing.JPanel();
        ClearSA_Btn = new javax.swing.JButton();
        CheckSA_Btn = new javax.swing.JButton();
        SubmitSA = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        Deposit_pnl = new javax.swing.JPanel();
        dAccount = new javax.swing.JLabel();
        DAccno_Txt = new javax.swing.JTextField();
        holderName_Txt = new javax.swing.JTextField();
        dName_Lbl = new javax.swing.JLabel();
        dBalance_Lbl = new javax.swing.JLabel();
        currentBalance_Txt = new javax.swing.JTextField();
        DEPAmount_Txt = new javax.swing.JTextField();
        dAmmount_Lbl = new javax.swing.JLabel();
        dType_Lbl = new javax.swing.JLabel();
        ACCType_Txt = new javax.swing.JTextField();
        DepositBonus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        bonusINFO_tarea = new javax.swing.JTextArea();
        total_Lbl = new javax.swing.JLabel();
        FinalDeposit_Txt = new javax.swing.JTextField();
        jSplitPane5 = new javax.swing.JSplitPane();
        wOption_pnl = new javax.swing.JPanel();
        ClearSA1 = new javax.swing.JButton();
        CheckSA1 = new javax.swing.JButton();
        SubmitSA1 = new javax.swing.JButton();
        withdrawal_pnl = new javax.swing.JPanel();
        wACCT = new javax.swing.JLabel();
        wName_Lbl = new javax.swing.JLabel();
        wBalance_Lbl = new javax.swing.JLabel();
        WHolder_Txt = new javax.swing.JTextField();
        DCurrentBalance_Txt = new javax.swing.JTextField();
        WAccno_Txt = new javax.swing.JTextField();
        WDRL_Lbl = new javax.swing.JLabel();
        Dwithdraw_Txt = new javax.swing.JTextField();
        mInterest_pnl = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        interestINFO_tarea = new javax.swing.JTextArea();
        CheckSA3_Btn = new javax.swing.JButton();
        processInterest_Btn = new javax.swing.JButton();
        day_Lbl = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        reports_pnl = new javax.swing.JTabbedPane();
        jSplitPane4 = new javax.swing.JSplitPane();
        rOptions_jbl = new javax.swing.JPanel();
        Generate_Btn = new javax.swing.JButton();
        RSubmit = new javax.swing.JButton();
        dReport_pnl = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        nCustomer_pnl = new javax.swing.JPanel();
        ACCTType_Lbl = new javax.swing.JLabel();
        FName_Lbl = new javax.swing.JLabel();
        ACCTNumber_Lbl = new javax.swing.JLabel();
        PhoneNum_Lbl = new javax.swing.JLabel();
        IDeposit_Lbl = new javax.swing.JLabel();
        Mail_Lbl = new javax.swing.JLabel();
        NewFName_Txt = new javax.swing.JTextField();
        LName_Lbl = new javax.swing.JLabel();
        NewLName_Txt = new javax.swing.JTextField();
        listOfAccountTypes = new javax.swing.JComboBox<>();
        NewMail_Txt = new javax.swing.JTextField();
        IDepositAMT_Txt = new javax.swing.JTextField();
        GeneratedAccountNo_Txt = new javax.swing.JTextField();
        NewPhoneNum_Txt = new javax.swing.JTextField();
        accNoGen_btn = new javax.swing.JButton();
        accNoGen1 = new javax.swing.JButton();
        PNumber_Lbl = new javax.swing.JLabel();
        Nationals_Lbl = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        jMenu1.setText("Menu");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jMenu1.add(logout);

        jMenuBar1.add(jMenu1);

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(997, 598));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        NewUser.setBackground(new java.awt.Color(255, 204, 255));

        savingsAcc_pnl.setBackground(new java.awt.Color(255, 255, 204));

        ClearSA_Btn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ClearSA_Btn.setText("Clear");

        CheckSA_Btn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CheckSA_Btn.setText("Check");

        SubmitSA.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SubmitSA.setText("Submit");

        javax.swing.GroupLayout dOption_pnlLayout = new javax.swing.GroupLayout(dOption_pnl);
        dOption_pnl.setLayout(dOption_pnlLayout);
        dOption_pnlLayout.setHorizontalGroup(
            dOption_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ClearSA_Btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(CheckSA_Btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(SubmitSA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dOption_pnlLayout.setVerticalGroup(
            dOption_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dOption_pnlLayout.createSequentialGroup()
                .addComponent(ClearSA_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(CheckSA_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 319, Short.MAX_VALUE)
                .addComponent(SubmitSA, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jSplitPane1.setLeftComponent(dOption_pnl);

        dAccount.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        dAccount.setText("Account No:");

        DAccno_Txt.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        DAccno_Txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DAccno_TxtActionPerformed(evt);
            }
        });

        holderName_Txt.setEditable(false);
        holderName_Txt.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        holderName_Txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                holderName_TxtActionPerformed(evt);
            }
        });

        dName_Lbl.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        dName_Lbl.setText("Holder Name:");

        dBalance_Lbl.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        dBalance_Lbl.setText("Current Balance: ");

        currentBalance_Txt.setEditable(false);
        currentBalance_Txt.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        currentBalance_Txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentBalance_TxtActionPerformed(evt);
            }
        });

        DEPAmount_Txt.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        DEPAmount_Txt.setText("0.00");
        DEPAmount_Txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DEPAmount_TxtActionPerformed(evt);
            }
        });

        dAmmount_Lbl.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        dAmmount_Lbl.setText("Deposit Amount:");

        dType_Lbl.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        dType_Lbl.setText("Account Type");

        ACCType_Txt.setEditable(false);
        ACCType_Txt.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        ACCType_Txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ACCType_TxtActionPerformed(evt);
            }
        });

        DepositBonus.setText("Bonus Calculate");
        DepositBonus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepositBonusActionPerformed(evt);
            }
        });

        bonusINFO_tarea.setEditable(false);
        bonusINFO_tarea.setColumns(20);
        bonusINFO_tarea.setRows(5);
        bonusINFO_tarea.setText("QUINN BANK DAILY DEPOSIT BONUS - DECEMBER / APRIL (SESONAL))\n\nNormal Savings : 1.25%\nBonus Savings : 3%\nPremier Savings : 7%");
        jScrollPane1.setViewportView(bonusINFO_tarea);

        total_Lbl.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        total_Lbl.setText("Final Total:");

        FinalDeposit_Txt.setEditable(false);
        FinalDeposit_Txt.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        FinalDeposit_Txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinalDeposit_TxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Deposit_pnlLayout = new javax.swing.GroupLayout(Deposit_pnl);
        Deposit_pnl.setLayout(Deposit_pnlLayout);
        Deposit_pnlLayout.setHorizontalGroup(
            Deposit_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Deposit_pnlLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(Deposit_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Deposit_pnlLayout.createSequentialGroup()
                        .addComponent(total_Lbl)
                        .addGap(43, 43, 43)
                        .addGroup(Deposit_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FinalDeposit_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DepositBonus))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(Deposit_pnlLayout.createSequentialGroup()
                        .addGroup(Deposit_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Deposit_pnlLayout.createSequentialGroup()
                                .addComponent(dAccount)
                                .addGap(33, 33, 33)
                                .addComponent(DAccno_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Deposit_pnlLayout.createSequentialGroup()
                                .addGroup(Deposit_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dName_Lbl)
                                    .addComponent(dType_Lbl)
                                    .addGroup(Deposit_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(dAmmount_Lbl)
                                        .addComponent(dBalance_Lbl)))
                                .addGap(4, 4, 4)
                                .addGroup(Deposit_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ACCType_Txt, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                                    .addComponent(holderName_Txt, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                                    .addComponent(currentBalance_Txt, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                                    .addComponent(DEPAmount_Txt)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 657, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(242, Short.MAX_VALUE))))
        );
        Deposit_pnlLayout.setVerticalGroup(
            Deposit_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Deposit_pnlLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(Deposit_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dAccount)
                    .addComponent(DAccno_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(Deposit_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dName_Lbl)
                    .addComponent(holderName_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Deposit_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dBalance_Lbl)
                    .addComponent(currentBalance_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Deposit_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dType_Lbl)
                    .addComponent(ACCType_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(Deposit_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dAmmount_Lbl)
                    .addComponent(DEPAmount_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Deposit_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Deposit_pnlLayout.createSequentialGroup()
                        .addComponent(total_Lbl)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Deposit_pnlLayout.createSequentialGroup()
                        .addComponent(FinalDeposit_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(DepositBonus)
                .addGap(53, 53, 53))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Deposit_pnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Deposit_pnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(jPanel5);

        savingsAcc_pnl.addTab("Deposits", jSplitPane1);

        ClearSA1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ClearSA1.setText("Clear");

        CheckSA1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CheckSA1.setText("Check");

        SubmitSA1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SubmitSA1.setText("Submit");

        javax.swing.GroupLayout wOption_pnlLayout = new javax.swing.GroupLayout(wOption_pnl);
        wOption_pnl.setLayout(wOption_pnlLayout);
        wOption_pnlLayout.setHorizontalGroup(
            wOption_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ClearSA1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(CheckSA1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(SubmitSA1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        wOption_pnlLayout.setVerticalGroup(
            wOption_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wOption_pnlLayout.createSequentialGroup()
                .addComponent(ClearSA1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(CheckSA1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 319, Short.MAX_VALUE)
                .addComponent(SubmitSA1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jSplitPane5.setLeftComponent(wOption_pnl);

        wACCT.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        wACCT.setText("Account No:");

        wName_Lbl.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        wName_Lbl.setText("Holder Name:");

        wBalance_Lbl.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        wBalance_Lbl.setText("Current Balance: ");

        WHolder_Txt.setEditable(false);
        WHolder_Txt.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        WHolder_Txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WHolder_TxtActionPerformed(evt);
            }
        });

        DCurrentBalance_Txt.setEditable(false);
        DCurrentBalance_Txt.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        DCurrentBalance_Txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DCurrentBalance_TxtActionPerformed(evt);
            }
        });

        WAccno_Txt.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        WAccno_Txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WAccno_TxtActionPerformed(evt);
            }
        });

        WDRL_Lbl.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        WDRL_Lbl.setText("Withdraw Amount:");

        Dwithdraw_Txt.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        Dwithdraw_Txt.setText("0.00");
        Dwithdraw_Txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dwithdraw_TxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout withdrawal_pnlLayout = new javax.swing.GroupLayout(withdrawal_pnl);
        withdrawal_pnl.setLayout(withdrawal_pnlLayout);
        withdrawal_pnlLayout.setHorizontalGroup(
            withdrawal_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(withdrawal_pnlLayout.createSequentialGroup()
                .addGroup(withdrawal_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(withdrawal_pnlLayout.createSequentialGroup()
                        .addGroup(withdrawal_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(withdrawal_pnlLayout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addGroup(withdrawal_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(wACCT)
                                    .addComponent(wName_Lbl))
                                .addGap(24, 24, 24))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, withdrawal_pnlLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(wBalance_Lbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(withdrawal_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(WAccno_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(WHolder_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DCurrentBalance_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(withdrawal_pnlLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(WDRL_Lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Dwithdraw_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(637, Short.MAX_VALUE))
        );
        withdrawal_pnlLayout.setVerticalGroup(
            withdrawal_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(withdrawal_pnlLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(withdrawal_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wACCT)
                    .addComponent(WAccno_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(withdrawal_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wName_Lbl)
                    .addComponent(WHolder_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(withdrawal_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(wBalance_Lbl)
                    .addComponent(DCurrentBalance_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(withdrawal_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WDRL_Lbl)
                    .addComponent(Dwithdraw_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(277, Short.MAX_VALUE))
        );

        jSplitPane5.setRightComponent(withdrawal_pnl);

        savingsAcc_pnl.addTab("Withdrawals", jSplitPane5);

        NewUser.addTab("Savings Account", savingsAcc_pnl);

        mInterest_pnl.setBackground(new java.awt.Color(255, 204, 255));

        interestINFO_tarea.setEditable(false);
        interestINFO_tarea.setColumns(20);
        interestINFO_tarea.setFont(new java.awt.Font("MS Gothic", 1, 18)); // NOI18N
        interestINFO_tarea.setRows(5);
        interestINFO_tarea.setText("BUILDING ECONOMY TOGETHER, EMPOWERING LIVES - QUINN BANK (MANUAL INTERST PROCESSING SYSTEM)\n\n\nDate: 22th every month (Double Interst on December Season)\n\n*Finance department verifies all interests and finals them by 28th.");
        jScrollPane2.setViewportView(interestINFO_tarea);

        CheckSA3_Btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CheckSA3_Btn.setText("FETCH ALL ACCOUNTS");

        processInterest_Btn.setBackground(java.awt.Color.orange);
        processInterest_Btn.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        processInterest_Btn.setForeground(java.awt.Color.red);
        processInterest_Btn.setText("PROCESS INTEREST");
        processInterest_Btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                processInterest_BtnMousePressed(evt);
            }
        });

        day_Lbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        day_Lbl.setText("Today:");

        date.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        date.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                datePropertyChange(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(day_Lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(processInterest_Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 962, Short.MAX_VALUE)
                            .addComponent(CheckSA3_Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(45, 45, 45))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(day_Lbl)
                    .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CheckSA3_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(processInterest_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(127, Short.MAX_VALUE))
        );

        mInterest_pnl.addTab("HOME", jPanel6);

        NewUser.addTab("Monthly Interests", mInterest_pnl);

        reports_pnl.setBackground(new java.awt.Color(204, 204, 255));

        Generate_Btn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Generate_Btn.setText("Generate");

        RSubmit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RSubmit.setText("Submit");

        javax.swing.GroupLayout rOptions_jblLayout = new javax.swing.GroupLayout(rOptions_jbl);
        rOptions_jbl.setLayout(rOptions_jblLayout);
        rOptions_jblLayout.setHorizontalGroup(
            rOptions_jblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Generate_Btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(RSubmit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        rOptions_jblLayout.setVerticalGroup(
            rOptions_jblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rOptions_jblLayout.createSequentialGroup()
                .addComponent(Generate_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 401, Short.MAX_VALUE)
                .addComponent(RSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jSplitPane4.setLeftComponent(rOptions_jbl);

        javax.swing.GroupLayout dReport_pnlLayout = new javax.swing.GroupLayout(dReport_pnl);
        dReport_pnl.setLayout(dReport_pnlLayout);
        dReport_pnlLayout.setHorizontalGroup(
            dReport_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 958, Short.MAX_VALUE)
        );
        dReport_pnlLayout.setVerticalGroup(
            dReport_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 506, Short.MAX_VALUE)
        );

        jSplitPane4.setRightComponent(dReport_pnl);

        reports_pnl.addTab("Daily Report", jSplitPane4);

        NewUser.addTab("Reports", reports_pnl);

        jPanel16.setBackground(new java.awt.Color(51, 51, 0));

        nCustomer_pnl.setBackground(new java.awt.Color(102, 102, 0));

        ACCTType_Lbl.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        ACCTType_Lbl.setText("Account Type");

        FName_Lbl.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        FName_Lbl.setText("First Name");

        ACCTNumber_Lbl.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        ACCTNumber_Lbl.setText("Account Number");

        PhoneNum_Lbl.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        PhoneNum_Lbl.setText("Phone                    +44");

        IDeposit_Lbl.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        IDeposit_Lbl.setText("Initial Deposit (£100)");

        Mail_Lbl.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Mail_Lbl.setText("Email");

        NewFName_Txt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        NewFName_Txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewFName_TxtActionPerformed(evt);
            }
        });

        LName_Lbl.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        LName_Lbl.setText("Last Name");

        NewLName_Txt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        listOfAccountTypes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        listOfAccountTypes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--SELECT ACCOUNT TYPE--", "NORMAL SAVINGS", "BONUS SAVINGS", "PRIMIER SAVINGS" }));

        NewMail_Txt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        IDepositAMT_Txt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        IDepositAMT_Txt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        IDepositAMT_Txt.setText("0.00");

        GeneratedAccountNo_Txt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        GeneratedAccountNo_Txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GeneratedAccountNo_TxtActionPerformed(evt);
            }
        });

        NewPhoneNum_Txt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        accNoGen_btn.setBackground(new java.awt.Color(51, 51, 51));
        accNoGen_btn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        accNoGen_btn.setForeground(new java.awt.Color(255, 255, 255));
        accNoGen_btn.setText("Generate");
        accNoGen_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accNoGen_btnActionPerformed(evt);
            }
        });

        accNoGen1.setBackground(new java.awt.Color(0, 0, 153));
        accNoGen1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        accNoGen1.setForeground(new java.awt.Color(255, 255, 255));
        accNoGen1.setText("Create Account");

        PNumber_Lbl.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        PNumber_Lbl.setText("Passport Number / ID Number (Foreign Nationals)");

        Nationals_Lbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout nCustomer_pnlLayout = new javax.swing.GroupLayout(nCustomer_pnl);
        nCustomer_pnl.setLayout(nCustomer_pnlLayout);
        nCustomer_pnlLayout.setHorizontalGroup(
            nCustomer_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nCustomer_pnlLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(nCustomer_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nCustomer_pnlLayout.createSequentialGroup()
                        .addGroup(nCustomer_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(nCustomer_pnlLayout.createSequentialGroup()
                                .addGroup(nCustomer_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(nCustomer_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(ACCTType_Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                                        .addComponent(Mail_Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(PhoneNum_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(IDeposit_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ACCTNumber_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(nCustomer_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(listOfAccountTypes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(nCustomer_pnlLayout.createSequentialGroup()
                                        .addGroup(nCustomer_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(NewMail_Txt, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(NewPhoneNum_Txt, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(IDepositAMT_Txt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                                            .addComponent(GeneratedAccountNo_Txt, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(31, 31, 31)
                                        .addComponent(accNoGen_btn))))
                            .addGroup(nCustomer_pnlLayout.createSequentialGroup()
                                .addGroup(nCustomer_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LName_Lbl)
                                    .addComponent(FName_Lbl))
                                .addGap(106, 106, 106)
                                .addGroup(nCustomer_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(NewLName_Txt)
                                    .addGroup(nCustomer_pnlLayout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(NewFName_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 215, Short.MAX_VALUE)
                        .addComponent(accNoGen1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(nCustomer_pnlLayout.createSequentialGroup()
                        .addComponent(PNumber_Lbl)
                        .addGap(18, 18, 18)
                        .addComponent(Nationals_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        nCustomer_pnlLayout.setVerticalGroup(
            nCustomer_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nCustomer_pnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(nCustomer_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nCustomer_pnlLayout.createSequentialGroup()
                        .addComponent(FName_Lbl)
                        .addGap(20, 20, 20)
                        .addComponent(LName_Lbl))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nCustomer_pnlLayout.createSequentialGroup()
                        .addComponent(NewFName_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(NewLName_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(nCustomer_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ACCTType_Lbl)
                    .addComponent(listOfAccountTypes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(nCustomer_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nationals_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PNumber_Lbl))
                .addGap(18, 18, 18)
                .addGroup(nCustomer_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Mail_Lbl)
                    .addComponent(NewMail_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(nCustomer_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PhoneNum_Lbl)
                    .addComponent(NewPhoneNum_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(nCustomer_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IDeposit_Lbl)
                    .addComponent(IDepositAMT_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(nCustomer_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nCustomer_pnlLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addComponent(accNoGen1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(nCustomer_pnlLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(nCustomer_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ACCTNumber_Lbl)
                            .addComponent(GeneratedAccountNo_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(accNoGen_btn))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(nCustomer_pnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addContainerGap(105, Short.MAX_VALUE)
                .addComponent(nCustomer_pnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        NewUser.addTab("NEW Customer", jPanel16);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/QUINN_LOGO.gif"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Bodoni MT", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("QUINN BANK");

        jLabel4.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Guarding Day & Night");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1)
                        .addGap(185, 185, 185)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(NewUser, javax.swing.GroupLayout.PREFERRED_SIZE, 1062, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NewUser)
                .addContainerGap())
        );

        jMenu2.setText("File");

        jMenuItem1.setText("Manager Access");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("Logout");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar2.add(jMenu2);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NewFName_TxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewFName_TxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewFName_TxtActionPerformed

    private void accNoGen_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accNoGen_btnActionPerformed
        // Token Generator to Generate New Account Numbers
        String AccountType = (String) listOfAccountTypes.getSelectedItem();
         if(AccountType == "--SELECT ACCOUNT TYPE--")
        {
            JOptionPane.showMessageDialog(null, 
                              "Please An Account Type !", 
                              "Account Generation Halted!", 
                              JOptionPane.WARNING_MESSAGE);
        }
        else if(AccountType == "NORMAL SAVINGS")
        {
            int generatedAccount = basic;
            basic += 1;

            GeneratedAccountNo_Txt.setText(String.valueOf(generatedAccount));
        }
        else if(AccountType == "BONUS SAVINGS")
        {
            int generatedAccount = bonus;
            bonus += 1;

            GeneratedAccountNo_Txt.setText(String.valueOf(generatedAccount));
        }
        else if(AccountType == "PRIMIER SAVINGS")
        {
            int generatedAccount = premier;
            premier += 1;

            GeneratedAccountNo_Txt.setText(String.valueOf(generatedAccount));
        }
    }//GEN-LAST:event_accNoGen_btnActionPerformed

    private void GeneratedAccountNo_TxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GeneratedAccountNo_TxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GeneratedAccountNo_TxtActionPerformed

    private void WHolder_TxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WHolder_TxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WHolder_TxtActionPerformed

    private void DCurrentBalance_TxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DCurrentBalance_TxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DCurrentBalance_TxtActionPerformed

    private void WAccno_TxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WAccno_TxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WAccno_TxtActionPerformed

    private void Dwithdraw_TxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dwithdraw_TxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Dwithdraw_TxtActionPerformed

    private void DAccno_TxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DAccno_TxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DAccno_TxtActionPerformed

    private void holderName_TxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_holderName_TxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_holderName_TxtActionPerformed

    private void currentBalance_TxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentBalance_TxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_currentBalance_TxtActionPerformed

    private void DEPAmount_TxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DEPAmount_TxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DEPAmount_TxtActionPerformed

    private void ACCType_TxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ACCType_TxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ACCType_TxtActionPerformed

    private void FinalDeposit_TxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinalDeposit_TxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FinalDeposit_TxtActionPerformed

    private void DepositBonusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepositBonusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DepositBonusActionPerformed

    private void processInterest_BtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_processInterest_BtnMousePressed
        // NOTIFIES AGENT ABOUT INTEREST PROCESS AND BLOCKS MULTIPLE CALCULATIONS
        // COLOUR CHANGES AND BUTTON DISABLED WHEN CLICKED
    processInterest_Btn.setBackground(Color.GREEN);
    processInterest_Btn.setForeground(Color.BLACK);
    processInterest_Btn.setEnabled(false);
    processInterest_Btn.setText("Done");
    
    }//GEN-LAST:event_processInterest_BtnMousePressed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed

    }//GEN-LAST:event_logoutActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
     
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
         //Closing Form and Reopening the Login Screeen
        Access a1 = new Access();
        a1.setVisible(true);
        //closes the login form prevent unnecessary tab creation
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void datePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_datePropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_datePropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Teller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Teller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Teller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Teller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Teller().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ACCTNumber_Lbl;
    private javax.swing.JLabel ACCTType_Lbl;
    private javax.swing.JTextField ACCType_Txt;
    private javax.swing.JButton CheckSA1;
    private javax.swing.JButton CheckSA3_Btn;
    private javax.swing.JButton CheckSA_Btn;
    private javax.swing.JButton ClearSA1;
    private javax.swing.JButton ClearSA_Btn;
    private javax.swing.JTextField DAccno_Txt;
    private javax.swing.JTextField DCurrentBalance_Txt;
    private javax.swing.JTextField DEPAmount_Txt;
    private javax.swing.JButton DepositBonus;
    private javax.swing.JPanel Deposit_pnl;
    private javax.swing.JTextField Dwithdraw_Txt;
    private javax.swing.JLabel FName_Lbl;
    private javax.swing.JTextField FinalDeposit_Txt;
    private javax.swing.JButton Generate_Btn;
    private javax.swing.JTextField GeneratedAccountNo_Txt;
    private javax.swing.JTextField IDepositAMT_Txt;
    private javax.swing.JLabel IDeposit_Lbl;
    private javax.swing.JLabel LName_Lbl;
    private javax.swing.JLabel Mail_Lbl;
    private javax.swing.JTextField Nationals_Lbl;
    private javax.swing.JTextField NewFName_Txt;
    private javax.swing.JTextField NewLName_Txt;
    private javax.swing.JTextField NewMail_Txt;
    private javax.swing.JTextField NewPhoneNum_Txt;
    private javax.swing.JTabbedPane NewUser;
    private javax.swing.JLabel PNumber_Lbl;
    private javax.swing.JLabel PhoneNum_Lbl;
    private javax.swing.JButton RSubmit;
    private javax.swing.JButton SubmitSA;
    private javax.swing.JButton SubmitSA1;
    private javax.swing.JTextField WAccno_Txt;
    private javax.swing.JLabel WDRL_Lbl;
    private javax.swing.JTextField WHolder_Txt;
    private javax.swing.JButton accNoGen1;
    private javax.swing.JButton accNoGen_btn;
    private javax.swing.JTextArea bonusINFO_tarea;
    private javax.swing.JTextField currentBalance_Txt;
    private javax.swing.JLabel dAccount;
    private javax.swing.JLabel dAmmount_Lbl;
    private javax.swing.JLabel dBalance_Lbl;
    private javax.swing.JLabel dName_Lbl;
    private javax.swing.JPanel dOption_pnl;
    private javax.swing.JPanel dReport_pnl;
    private javax.swing.JLabel dType_Lbl;
    private javax.swing.JLabel date;
    private javax.swing.JLabel day_Lbl;
    private javax.swing.JTextField holderName_Txt;
    private javax.swing.JTextArea interestINFO_tarea;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane4;
    private javax.swing.JSplitPane jSplitPane5;
    private javax.swing.JComboBox<String> listOfAccountTypes;
    private javax.swing.JMenuItem logout;
    private javax.swing.JTabbedPane mInterest_pnl;
    private javax.swing.JPanel nCustomer_pnl;
    private javax.swing.JButton processInterest_Btn;
    private javax.swing.JPanel rOptions_jbl;
    private javax.swing.JTabbedPane reports_pnl;
    private javax.swing.JTabbedPane savingsAcc_pnl;
    private javax.swing.JLabel total_Lbl;
    private javax.swing.JLabel wACCT;
    private javax.swing.JLabel wBalance_Lbl;
    private javax.swing.JLabel wName_Lbl;
    private javax.swing.JPanel wOption_pnl;
    private javax.swing.JPanel withdrawal_pnl;
    // End of variables declaration//GEN-END:variables
}
