
import DatabaseConnection.DBConnection;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hp-Pc
 */
public class UpdateTellers extends javax.swing.JFrame {

    /**
     * Creates new form UpdateTellers
     */
    Connection conn=null;
    PreparedStatement ps=null;
    
    DBConnection db;
    
    public UpdateTellers() {
        initComponents();
        
        db=new DBConnection();
        
        //Only closes this window
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        tellerId_Lbl = new javax.swing.JLabel();
        Username_Lbl = new javax.swing.JLabel();
        Password_Lbl = new javax.swing.JLabel();
        tUpdate_btn = new javax.swing.JButton();
        Username_Txt = new javax.swing.JTextField();
        branch_Lbl = new javax.swing.JLabel();
        Branch_Txt = new javax.swing.JTextField();
        TellerId_Txt = new javax.swing.JTextField();
        Password_Txt = new javax.swing.JTextField();
        close = new javax.swing.JButton();
        Address_Txt = new javax.swing.JLabel();
        city_Txt = new javax.swing.JLabel();
        email_Txt = new javax.swing.JLabel();
        lAddress_Txt = new javax.swing.JTextField();
        cCity_Txt = new javax.swing.JTextField();
        Email_Txt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 123, 146));
        setUndecorated(true);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(0, 123, 146));

        jPanel1.setBackground(new java.awt.Color(18, 63, 72));

        tellerId_Lbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tellerId_Lbl.setForeground(new java.awt.Color(255, 255, 255));
        tellerId_Lbl.setText("System Login ID");

        Username_Lbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Username_Lbl.setForeground(new java.awt.Color(255, 255, 255));
        Username_Lbl.setText("Username");

        Password_Lbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Password_Lbl.setForeground(new java.awt.Color(255, 255, 255));
        Password_Lbl.setText("Password");

        tUpdate_btn.setBackground(new java.awt.Color(0, 0, 51));
        tUpdate_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tUpdate_btn.setForeground(new java.awt.Color(255, 255, 255));
        tUpdate_btn.setText("Update");
        tUpdate_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tUpdate_btnActionPerformed(evt);
            }
        });

        branch_Lbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        branch_Lbl.setForeground(new java.awt.Color(255, 255, 255));
        branch_Lbl.setText("Branch");

        close.setBackground(new java.awt.Color(0, 123, 146));
        close.setForeground(new java.awt.Color(255, 255, 255));
        close.setText("X");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });

        Address_Txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Address_Txt.setForeground(new java.awt.Color(255, 255, 255));
        Address_Txt.setText("Lane Address");

        city_Txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        city_Txt.setForeground(new java.awt.Color(255, 255, 255));
        city_Txt.setText("City");

        email_Txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        email_Txt.setForeground(new java.awt.Color(255, 255, 255));
        email_Txt.setText("Email Address");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tUpdate_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Username_Lbl)
                                .addComponent(tellerId_Lbl)
                                .addComponent(branch_Lbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Password_Lbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(city_Txt)
                            .addComponent(Address_Txt)
                            .addComponent(email_Txt))
                        .addGap(84, 84, 84)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Username_Txt)
                            .addComponent(Branch_Txt)
                            .addComponent(Password_Txt)
                            .addComponent(TellerId_Txt)
                            .addComponent(lAddress_Txt, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                            .addComponent(cCity_Txt)
                            .addComponent(Email_Txt))))
                .addGap(105, 105, 105))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(close)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(close)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TellerId_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tellerId_Lbl))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Username_Lbl)
                            .addComponent(Username_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Password_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Password_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(branch_Lbl)
                            .addComponent(Branch_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addComponent(Address_Txt))
                    .addComponent(lAddress_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(city_Txt)
                    .addComponent(cCity_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email_Txt)
                    .addComponent(Email_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(tUpdate_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tUpdate_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tUpdate_btnActionPerformed

        try {
            conn=DriverManager.getConnection(db.DatabaseConnectionUrl());
            String sql="UPDATE dbo.SystemLogin SET Username =?, Password =? where SystemLoginID =?";
            ps=conn.prepareStatement(sql);
            ps.setString(1,Username_Txt.getText());
            ps.setString(2,Password_Txt.getText());
            ps.setString(3,TellerId_Txt.getText());
            ps.executeUpdate();
            
            String Sql2="Update dbo.Teller set Branch=?, LaneAddress=?,City=?,EmailAddress=? where slSystemLoginID=?";
            ps=conn.prepareStatement(Sql2);
            ps.setString(1, Branch_Txt.getText());
            ps.setString(2, lAddress_Txt.getText());
            ps.setString(3, cCity_Txt.getText());
            ps.setString(4, Email_Txt.getText());
            ps.setString(5, TellerId_Txt.getText());
            ps.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "Update Successful");
            
            //closes the window
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(UpdateTellers.class.getName()).log(Level.SEVERE, null, ex);
        }
     
        
        
    }//GEN-LAST:event_tUpdate_btnActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        //Closes the Updatinf Form
        this.setVisible(false);
    }//GEN-LAST:event_closeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateTellers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateTellers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateTellers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateTellers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateTellers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Address_Txt;
    private javax.swing.JTextField Branch_Txt;
    private javax.swing.JTextField Email_Txt;
    private javax.swing.JLabel Password_Lbl;
    private javax.swing.JTextField Password_Txt;
    private javax.swing.JTextField TellerId_Txt;
    private javax.swing.JLabel Username_Lbl;
    private javax.swing.JTextField Username_Txt;
    private javax.swing.JLabel branch_Lbl;
    private javax.swing.JTextField cCity_Txt;
    private javax.swing.JLabel city_Txt;
    private javax.swing.JButton close;
    private javax.swing.JLabel email_Txt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField lAddress_Txt;
    private javax.swing.JButton tUpdate_btn;
    private javax.swing.JLabel tellerId_Lbl;
    // End of variables declaration//GEN-END:variables
}
